/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shapes;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ann
 */
public class RectangleInfo extends javax.swing.JFrame implements Node{

    /**
     * Creates new form RectangleInfo
     */
    private Rectangle r;
    private Node parent;
    private Color borderColor;
    private Color fillColor;
    private Canvas drawings;
    private JComboBox<String> ComboBox;
      private  int flag1=0;
       private  int flag2=0;
    public RectangleInfo(Canvas mydrawingArea, JComboBox<String> ComboBox) {
        setTitle("Rectangle Specifications");
        initComponents();
        this.ComboBox=ComboBox;
        drawings=mydrawingArea;
        setVisible(true);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonSetColor = new javax.swing.JButton();
        jButtonFillColor = new javax.swing.JButton();
        jTextFieldPointX = new javax.swing.JTextField();
        jTextFieldPointY = new javax.swing.JTextField();
        jTextFieldLength = new javax.swing.JTextField();
        jTextFieldWidth = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Point x : ");

        jLabel2.setText("Point y :");

        jLabel3.setText("Width :");

        jLabel4.setText("Height :");

        jLabel5.setText("Set Color");

        jLabel6.setText("Set Fill Color");

        jButtonSetColor.setText("Choose color");
        jButtonSetColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetColorActionPerformed(evt);
            }
        });

        jButtonFillColor.setText("Choose color");
        jButtonFillColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFillColorActionPerformed(evt);
            }
        });

        jTextFieldPointX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPointXActionPerformed(evt);
            }
        });

        jTextFieldWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWidthActionPerformed(evt);
            }
        });

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonFillColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSetColor, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                        .addComponent(jTextFieldPointX, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldWidth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLength, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPointY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPointX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPointY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonSetColor))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButtonFillColor))
                .addGap(12, 12, 12)
                .addComponent(jButton3)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWidthActionPerformed

    private void jButtonFillColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFillColorActionPerformed
        // TODO add your handling code here:
        flag2++;
        fillColor=JColorChooser.showDialog(null, "Choose fillcolor", Color.WHITE);
    }//GEN-LAST:event_jButtonFillColorActionPerformed

    private void jTextFieldPointXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPointXActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldPointXActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      try{  String pointX=jTextFieldPointX.getText();
        String pointY=jTextFieldPointY.getText();
        String width=jTextFieldLength.getText();
        String height=jTextFieldWidth.getText();
        int  x = Integer.parseInt(pointX);
        int  y = Integer.parseInt(pointY);
        int  w = Integer.parseInt(width);
        int  h = Integer.parseInt(height);
   
       if(x<0 || y<0 || w<1 || h<1 ){
       throw new NumberFormatException();}
        r=new Rectangle(new Point(x,y),w,h);
         if(flag1!=0&&flag2!=0)
        { r.setColor(borderColor);
          r.setFillColor(fillColor);}
        if(flag1!=0&&flag2==0)
        {r.setColor(borderColor);
        r.setFillColor(Color.BLACK);
        }
        if(flag1==0&&flag2!=0)
        {  r.setColor(Color.BLACK);
        r.setFillColor(fillColor);
        }
         if(flag1==0&&flag2==0)
         {  r.setFillColor(Color.BLACK);
         r.setColor(Color.BLACK);
         }
        ComboBox.addItem("Rectangle " + (ComboBox.getItemCount()+1));
        drawings.addShape(r);
        setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,"Kindly Check Your Data");
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonSetColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetColorActionPerformed
        // TODO add your handling code here:
        flag1++;
       borderColor=JColorChooser.showDialog(null, "Choose color", Color.black);
    }//GEN-LAST:event_jButtonSetColorActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonFillColor;
    private javax.swing.JButton jButtonSetColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldLength;
    private javax.swing.JTextField jTextFieldPointX;
    private javax.swing.JTextField jTextFieldPointY;
    private javax.swing.JTextField jTextFieldWidth;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getParentNode() {
       return parent;    
    }

    @Override
    public void setParentNode(Node node) {
       this.parent=node;
    }
}
