/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shapes;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ann
 */
public class CircleInfo extends javax.swing.JFrame implements Node{

    /**
     * Creates new form CircleInfo
     */private Node parent;
    private  Canvas drawings;
    private  Color borderColor;
    private  Color fillColor;
     private JComboBox<String> ComboBox;
     private Circle c;
     private  int flag1=0;
       private  int flag2=0;
       boolean flag=false;
    public CircleInfo(Canvas mydrawingArea,JComboBox<String> ComboBox) {
        initComponents();
         setTitle("Circle Specifications");
        setVisible(true);  
        this.ComboBox=ComboBox;
        drawings=mydrawingArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveButton = new javax.swing.JButton();
        jTextFieldOfPointX = new javax.swing.JTextField();
        jTextFieldOfPointY = new javax.swing.JTextField();
        verradius = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonSetColor = new javax.swing.JButton();
        jButtonFillColor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        horradius = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        jTextFieldOfPointY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOfPointYActionPerformed(evt);
            }
        });

        jLabel1.setText("Point x :");

        jLabel2.setText("Point y :");

        jLabel3.setText(" Vertical Diameter :");

        jLabel4.setText("Set Color ");

        jLabel5.setText("Set Fill Color");

        jButtonSetColor.setText("Choose Color");
        jButtonSetColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetColorActionPerformed(evt);
            }
        });

        jButtonFillColor.setText("Choose Color");
        jButtonFillColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFillColorActionPerformed(evt);
            }
        });

        jLabel6.setText("Horizontal Diameter");

        horradius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horradiusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldOfPointX, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                        .addComponent(jTextFieldOfPointY)
                                        .addComponent(verradius))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonFillColor)
                                            .addComponent(jButtonSetColor))
                                        .addGap(46, 46, 46))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(SaveButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(horradius, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOfPointX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOfPointY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verradius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(horradius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButtonSetColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFillColor)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addComponent(SaveButton)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldOfPointYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOfPointYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOfPointYActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
       try{ String pointX=jTextFieldOfPointX.getText();
        String pointY=jTextFieldOfPointY.getText();
        String ver_radius=verradius.getText();
        String hr_radius=horradius.getText();
        
        
        int  x = Integer.parseInt(pointX);
        int  y = Integer.parseInt(pointY);
        int  vr = Integer.parseInt(ver_radius);
        int hr=Integer.parseInt(hr_radius);
         
       if(vr<1 ||hr<1|| x<0 || y<0)
       {throw new NumberFormatException(); }else{
        c=new Circle(new Point(x,y),vr,hr);
        if(flag1!=0&&flag2!=0)
        { c.setColor(borderColor);
          c.setFillColor(fillColor);}
        if(flag1!=0&&flag2==0)
        {c.setColor(borderColor);
        c.setFillColor(Color.BLACK);
        }
        if(flag1==0&&flag2!=0)
        {  c.setColor(Color.BLACK);
        c.setFillColor(fillColor);
        }
         if(flag1==0&&flag2==0)
         {  c.setFillColor(Color.BLACK);
         c.setColor(Color.BLACK);
         }
        ComboBox.addItem("Oval " + (ComboBox.getItemCount()+1));
        drawings.addShape(c);
       // flag=true;
         setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);}
       }catch(Exception e){JOptionPane.showMessageDialog(null,"Kindly Check Your Data");}
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void jButtonSetColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetColorActionPerformed
        // TODO add your handling code here:
       flag1++;
        borderColor=JColorChooser.showDialog(null, "Choose color", Color.black);
    }//GEN-LAST:event_jButtonSetColorActionPerformed

    private void jButtonFillColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFillColorActionPerformed
        // TODO add your handling code here:
        flag2++;
        fillColor=JColorChooser.showDialog(null, "Choose fillcolor", Color.WHITE);
        
    }//GEN-LAST:event_jButtonFillColorActionPerformed

    private void horradiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horradiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horradiusActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
           setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField horradius;
    private javax.swing.JButton jButtonFillColor;
    private javax.swing.JButton jButtonSetColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldOfPointX;
    private javax.swing.JTextField jTextFieldOfPointY;
    private javax.swing.JTextField verradius;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getParentNode() {
      return parent;
    }

    @Override
    public void setParentNode(Node node) {
     this.parent=node;
    }
}
