/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shapes;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ann
 */
public class LineInfo extends javax.swing.JFrame implements Node {

    /**
     * Creates new form LineInfo
     */
    private Node parent;
    private Line l;
    private Color borderColor;
   private  Canvas drawings;
   private JComboBox<String> ComboBox;
     private  int flag1=0;
       private  int flag2=0;
    public LineInfo(Canvas mydrawingArea,JComboBox<String> ComboBox) {
        initComponents();
         setTitle("Line Specifications");
         this.ComboBox=ComboBox;
        drawings=mydrawingArea;
        setVisible(true);  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPointX = new javax.swing.JTextField();
        jTextFieldPointY = new javax.swing.JTextField();
        jTextFieldStartPoint = new javax.swing.JTextField();
        jTextFieldEndPoint = new javax.swing.JTextField();
        jButtonSetColor = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Point x :");

        jLabel2.setText("Point y :");

        jLabel3.setText("Start Point :");

        jLabel4.setText("End Point");

        jLabel5.setText("Set Color");

        jButtonSetColor.setText("Choose Color");
        jButtonSetColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetColorActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPointX)
                    .addComponent(jTextFieldPointY)
                    .addComponent(jTextFieldStartPoint)
                    .addComponent(jTextFieldEndPoint)
                    .addComponent(jButtonSetColor, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButtonSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPointX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPointY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldStartPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEndPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonSetColor))
                .addGap(18, 18, 18)
                .addComponent(jButtonSave)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
      try{  String pointX=jTextFieldPointX.getText();
        String pointY=jTextFieldPointY.getText();
        String length=jTextFieldStartPoint.getText();
        String width=jTextFieldEndPoint.getText();
        int  x = Integer.parseInt(pointX);
        int  y = Integer.parseInt(pointY);
        int  s = Integer.parseInt(length);
        int  e = Integer.parseInt(width);
        if(x<0 || y<0 || s<0 || e<0){throw new NumberFormatException();}
        l=new Line(new Point(x,y),new Point(s,e));
         if(flag1!=0)
         {l.setColor(borderColor);
         l.setFillColor(Color.BLACK);
         }
         if(flag1 ==0)
         {l.setColor(Color.BLACK);
         l.setFillColor(Color.BLACK);
         } 
         
        ComboBox.addItem("Line " + (ComboBox.getItemCount()+1));
        drawings.addShape(l);
         setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);}catch(Exception e){JOptionPane.showMessageDialog(null,"Kindly Check Your Data");}
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSetColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetColorActionPerformed
        // TODO add your handling code here:
         flag1++;
       
       borderColor=JColorChooser.showDialog(null, "Choose color", Color.black);
    }//GEN-LAST:event_jButtonSetColorActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
           setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSetColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldEndPoint;
    private javax.swing.JTextField jTextFieldPointX;
    private javax.swing.JTextField jTextFieldPointY;
    private javax.swing.JTextField jTextFieldStartPoint;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getParentNode() {
    return parent;  
    }

    @Override
    public void setParentNode(Node node) {
     this.parent=node;  
    }
}
