/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shapes;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ann
 */

public class SquareInfo extends javax.swing.JFrame implements Node{

    /**
     * Creates new form SquareInfo
     */private Square s;
     private Color borderColor;
     private Color fillColor;
   private  Canvas drawings;
      private JComboBox<String> ComboBox;
    private Node parent;
     private  int flag1=0;
       private  int flag2=0;
    public SquareInfo(Canvas mydrawingArea,JComboBox<String> ComboBox) {
        initComponents();
        setTitle("Square Properties");
        this.ComboBox=ComboBox;
        drawings=mydrawingArea;
        setVisible(true);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPointX = new javax.swing.JTextField();
        jTextFieldPointY = new javax.swing.JTextField();
        jTextFieldSide = new javax.swing.JTextField();
        jButtonSetColor = new javax.swing.JButton();
        jButtonFillColor = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Point x :");

        jLabel2.setText("Point y :");

        jLabel3.setText("Side");

        jLabel5.setText("Set Color");

        jLabel6.setText("Set Fill Color");

        jButtonSetColor.setText("Choose Color");
        jButtonSetColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetColorActionPerformed(evt);
            }
        });

        jButtonFillColor.setText("Choose Color");
        jButtonFillColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFillColorActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonFillColor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSetColor)
                            .addComponent(jTextFieldPointX, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPointY, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jTextFieldSide))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButtonSave)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPointX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPointY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonSetColor))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButtonFillColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSave)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
     try {  String pointX=jTextFieldPointX.getText();
        String pointY=jTextFieldPointY.getText();
        String length=jTextFieldSide.getText();
        int  x = Integer.parseInt(pointX);
        int  y = Integer.parseInt(pointY);
        int  l = Integer.parseInt(length);
        if(x<0 || y<0 || l<1 )
        {throw new NumberFormatException();}
        s=new Square(new Point(x,y),l);
         if(flag1!=0&&flag2!=0)
        { s.setColor(borderColor);
          s.setFillColor(fillColor);}
        if(flag1!=0&&flag2==0)
        {s.setColor(borderColor);
        s.setFillColor(Color.BLACK);
        }
        if(flag1==0&&flag2!=0)
        {  s.setColor(Color.BLACK);
        s.setFillColor(fillColor);
        }
         if(flag1==0&&flag2==0)
         {  s.setFillColor(Color.BLACK);
         s.setColor(Color.BLACK);
         }
        ComboBox.addItem("Square " + (ComboBox.getItemCount()+1));
        drawings.addShape(s);
         setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
     }catch(Exception e){
     JOptionPane.showMessageDialog(null,"Kindly Check Your Data");}
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSetColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetColorActionPerformed
        // TODO add your handling code here:
        flag1++;
        borderColor=JColorChooser.showDialog(null, "Choose color", Color.black);
    }//GEN-LAST:event_jButtonSetColorActionPerformed

    private void jButtonFillColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFillColorActionPerformed
        // TODO add your handling code here:
        flag2++;
        fillColor=JColorChooser.showDialog(null, "Choose fillcolor", Color.WHITE);
    }//GEN-LAST:event_jButtonFillColorActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
           setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFillColor;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSetColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldPointX;
    private javax.swing.JTextField jTextFieldPointY;
    private javax.swing.JTextField jTextFieldSide;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getParentNode() {
     return parent;  
    }

    @Override
    public void setParentNode(Node node) {
    this.parent=node; 
    }
}
